@echo off
start cmd /c "python main.py --logic RayhanGreedy --email iodwadawawaj@gmail.com --name RAYYY1 --password aalkd --team etimo"
start cmd /c "python main.py --logic RayhanGreedy --email stnaodwadawa3waj@gmail.com --name RAYYY2 --password asalkd --team etimo"
start cmd /c "python main.py --logic RayhanGreedy --email stnasdi3wawaj2@gmail.com --name RAYYY3 --password asllkd --team etimo"
start cmd /c "python main.py --logic RayhanGreedy --email stnasdiodawaj@gmail.com --name RAYYY4 --password adkalkd --team etimo"
start cmd /c "python main.py --logic RayhanGreedy --email stnasdiod3@gmail.com --name RAYYY5 --password aslalkd --team etimo"
@REM start cmd /c "python main.py --logic AlucardGreedy --email stnasdioj@gmail.com --name mybot --password asldkalkd --team etimo"
@REM start cmd /c "python main.py --logic Kejar --email=test2333333@email.com --name=stima2 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Kejar --email=test41@email.com --name=stima3 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic Kejar --email=test51@email.com --name=stima1 --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic AlucardGreedy --email=test6@email.com --name=ALUCARD --password=123456 --team etimo"
@REM start cmd /c "python main.py --logic AlucardGreedy --email=test7@email.com --name=stima2 --password=123456 --team etimo"
