name: Python package

on:
  push:
    branches:
      - main 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Move to src directory
        run: cd src/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
        continue-on-error: true  # Continue to the next step even if this step fails

      - name: Check for errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Error: main.py failed to run successfully."
            exit 1
          fi

